# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b592f6b30431fac8d607f05d8c76bb1c"
name = "vite-store-ext"
handle = "vite-store-ext"
application_url = "https://hairy-strip-cent-liz.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "hellostorexyz.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_online_store_pages,read_products,read_themes,write_products,write_themes"

[auth]
redirect_urls = [
  "https://hairy-strip-cent-liz.trycloudflare.com/auth/callback",
  "https://hairy-strip-cent-liz.trycloudflare.com/auth/shopify/callback",
  "https://hairy-strip-cent-liz.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
