# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d3d070cea5fca7ab9ded6a39b7b5f856"
name = "Kodex"
handle = "kodex"
application_url = "https://cyprus-ext-proposed-antenna.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
dev_store_url = "my-great-shop-1.myshopify.com"
automatically_update_urls_on_dev = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_online_store_pages,read_themes,write_themes"

[auth]
redirect_urls = [
  "https://cyprus-ext-proposed-antenna.trycloudflare.com/auth/callback",
  "https://cyprus-ext-proposed-antenna.trycloudflare.com/auth/shopify/callback",
  "https://cyprus-ext-proposed-antenna.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
