# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3a9ba6e9b339bd49d6de03f53780e317"
name = "Test-001"
handle = "test-16361"
application_url = "https://artificial-coverage-west-forward.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "hellostorexyz.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_online_store_pages,read_products,read_themes,write_products,write_themes"

[auth]
redirect_urls = [
  "https://artificial-coverage-west-forward.trycloudflare.com/auth/callback",
  "https://artificial-coverage-west-forward.trycloudflare.com/auth/shopify/callback",
  "https://artificial-coverage-west-forward.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
